typography_spectrum: 0.8953579550143331
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.7017891383729875
  lightness: 0.3637412094976753
  saturation: 0.4074905870947987
  rhythmicContrast: 0.07197526306845248
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8920086668804288
analytics:
  google: null
  facebook: null
  twitter: null
name: Freesprung
cta:
  domain: null
  bucket: null
  version: null
navigation: []
favicon: null
title: Freesprung
purpose: []
