layout_spectrum: 0.6510639
color:
  saturation: 0
  brandStrength: 0.393617
  lightness: 0.2978723
  rhythmicContrast: 0.5765957
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.5319149
name: Freesprung
