typography_spectrum: 0.4788
color:
  brandColors:
    - '#000000'
    - '#5f5f5f'
    - '#f8fdfd'
    - '#94b2ce'
    - '#798794'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.54021
analytics:
  google: null
  facebook: null
  twitter: null
name: Freesprung
cta:
  domain: null
  bucket: null
  version: null
navigation: []
favicon: null
title: Freesprung
purpose: []
