name: Freesprung
favicon: null
layout_spectrum: 0.61411
typography_spectrum: 0.4788
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5f5f5f'
    - '#f8fdfd'
    - '#94b2ce'
    - '#798794'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
