typography_spectrum: 0.4788
color:
  brandColors:
    - '#000000'
    - '#5f5f5f'
    - '#f8fdfd'
    - '#94b2ce'
    - '#798794'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.71573
analytics:
  google: null
  facebook: null
  twitter: null
name: Freesprung
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: fd5fb7c1-a00d-44c0-ae4a-8296098e9c08
    name: Polishing
    type: content
favicon: null
purpose: []
